json.extract! client, :id, 
					  :client_unique_number,
					  :client_rut,
					  :client_name1,
					  :client_name2,
					  :client_address1,
					  :client_address2,
					  :client_city,
					  :client_phone,
					  :client_fax,
					  :client_cell_phone,
					  :client_web_site,
					  :domain,
					  :created_at, :updated_at
json.url client_url(client, format: :json)