source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# A simple HTTP and REST client for Ruby, inspired style of specifying actions: get, put, post, delete.
gem 'rest-client', '~> 2.0'
# Gem to manage json files
gem 'json', '~> 1.8', '>= 1.8.3'
# is a Sass powered version of Materialize, a modern responsive front-end framework based on Material Design.
gem 'materialize-sass'
# Central point to collect locale data for use in Ruby on Rails.
gem 'rails-i18n', '~> 4.0.0'
# Gema para paginación 
gem 'will_paginate', '~> 3.1.0'
# Gema para visualizar will_paginate con materialize
gem 'will_paginate-materialize', '~> 0.1.0'
# Gema para crear backups
gem 'backup'
# Use Unicorn as the app server
gem 'unicorn'


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'



# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  
  # Replaces the standard Rails error page with a much better and more useful error page
  gem "better_errors"

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

